import type { ThemePack } from '@foliokit/cms-ui';

/**
 * Comic Book — halftone-cream marketplace pack.
 *
 * Authored-but-not-bundled: exported from `@foliokit/cms-ui/marketplace-preview`,
 * intentionally NOT re-exported from the root barrel. Consumers that wish to
 * register this pack must import it from the subpath and pass it to
 * `provideThemePacks(...)`.
 *
 * Font loading relies on ThemePackService's dedup-by-URL: JetBrains Mono is
 * shared with the editorial pack, but each pack's fonts[] URL is distinct, so
 * the mono subset may be requested twice — harmless.
 */
export const COMIC_BOOK_PACK: ThemePack = {
  id: 'comic-book',
  name: 'Comic Book',
  version: '1.0.0',
  author: 'FolioKit',
  description: 'Halftone cream, inky borders, hard-offset shadows',
  // TODO: add `preview` thumbnail once marketplace UI supports it
  typography: {
    display: "'Bangers', 'Impact', sans-serif",
    body: "'Archivo', system-ui, sans-serif",
    mono: "'JetBrains Mono', 'Fira Code', monospace",
  },
  fonts: [
    {
      type: 'google',
      url: 'https://fonts.googleapis.com/css2?family=Bangers&display=swap',
    },
    {
      type: 'google',
      url: 'https://fonts.googleapis.com/css2?family=Archivo:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap',
    },
    {
      type: 'google',
      url: 'https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500&display=swap',
    },
  ],
  tokens: {
    light: {
      '--bg':             '#FBF5E8',
      '--bg-subtle':      '#F2E9D2',
      '--surface-0':      '#FFFDF5',
      '--surface-1':      '#FBF5E8',
      '--surface-2':      '#F2E9D2',
      '--surface-3':      '#E8DFC4',
      '--border':         '#0E0E0E',
      '--border-strong':  '#0E0E0E',
      '--border-accent':  '#C8102E',
      '--border-width':   '2px',
      '--text-primary':   '#1A1612',
      '--text-secondary': '#3A3530',
      '--text-muted':     '#6B645C',
      '--text-disabled':  '#A8A096',
      '--text-accent':    '#C8102E',
      '--text-on-accent': '#FFFDF5',
      '--text-on-dark':   '#FFFDF5',
      '--btn-primary-bg':    '#C8102E',
      '--btn-primary-text':  '#FFFDF5',
      '--btn-primary-hover': '#A30B24',
      '--logo-bg':   '#0E0E0E',
      '--logo-text': '#F7C948',
      '--logo-dot':  '#C8102E',
      '--focus-ring':   'rgba(200, 16, 46, 0.28)',
      '--focus-border': '#C8102E',
      '--shadow-sm': '2px 2px 0 #0E0E0E',
      '--shadow-md': '3px 3px 0 #0E0E0E',
      '--shadow-lg': '5px 5px 0 #0E0E0E',
      '--shadow-xl': '8px 8px 0 #0E0E0E',
      '--shadow-btn-primary': '3px 3px 0 #0E0E0E',
      '--nav-active-bg':    '#C8102E',
      '--nav-active-text':  '#FFFDF5',
      '--nav-active-color': '#FFFDF5',
      '--status-draft-bg':       '#E8DFC4',
      '--status-draft-text':     '#3A3530',
      '--status-published-bg':   '#2B5EAE',
      '--status-published-text': '#FFFDF5',
      '--status-scheduled-bg':   '#E8DFC4',
      '--status-scheduled-text': '#2B5EAE',
      '--status-archived-bg':    '#E8DFC4',
      '--status-archived-text':  '#6B645C',
    },
    dark: {
      '--bg':             '#1A1612',
      '--bg-subtle':      '#221D17',
      '--surface-0':      '#1A1612',
      '--surface-1':      '#221D17',
      '--surface-2':      '#2A241D',
      '--surface-3':      '#332A21',
      '--border':         '#F7C948',
      '--border-strong':  '#F7C948',
      '--border-accent':  '#E85D4E',
      '--border-width':   '2px',
      '--text-primary':   '#FBF5E8',
      '--text-secondary': '#D4C9B5',
      '--text-muted':     '#8A8070',
      '--text-disabled':  '#5C554B',
      '--text-accent':    '#E85D4E',
      '--text-on-accent': '#1A1612',
      '--text-on-dark':   '#FBF5E8',
      '--btn-primary-bg':    '#E85D4E',
      '--btn-primary-text':  '#1A1612',
      '--btn-primary-hover': '#FF7A6B',
      '--logo-bg':   '#F7C948',
      '--logo-text': '#1A1612',
      '--logo-dot':  '#E85D4E',
      '--focus-ring':   'rgba(247, 201, 72, 0.32)',
      '--focus-border': '#F7C948',
      '--shadow-sm': '2px 2px 0 #F7C948',
      '--shadow-md': '3px 3px 0 #F7C948',
      '--shadow-lg': '5px 5px 0 #F7C948',
      '--shadow-xl': '8px 8px 0 #F7C948',
      '--shadow-btn-primary': '3px 3px 0 #F7C948',
      '--nav-active-bg':    '#E85D4E',
      '--nav-active-text':  '#1A1612',
      '--nav-active-color': '#1A1612',
      '--status-draft-bg':       '#332A21',
      '--status-draft-text':     '#D4C9B5',
      '--status-published-bg':   '#6B93D6',
      '--status-published-text': '#1A1612',
      '--status-scheduled-bg':   '#332A21',
      '--status-scheduled-text': '#6B93D6',
      '--status-archived-bg':    '#332A21',
      '--status-archived-text':  '#8A8070',
    },
  },
};
