/**
 * Playwright globalSetup — shared across all three e2e apps.
 *
 * Responsibilities:
 *   1. Start Firebase emulators (Auth, Firestore, Storage) if they are not already running.
 *   2. Run the emulator seed script to populate test data.
 *
 * The admin storageState (authenticated session) is generated by the
 * dedicated `auth.setup.ts` project inside admin-e2e, which runs as a
 * Playwright `setup` project AFTER the webServer has started.
 */

import { execSync, spawn } from 'child_process';
import * as fs from 'fs';
import * as net from 'net';
import * as path from 'path';

const WORKSPACE_ROOT = path.join(__dirname, '..', '..');
const PID_FILE = path.join(WORKSPACE_ROOT, '.firebase', 'e2e-emulator.pid');

const EMULATOR_PORTS = {
  auth: 9099,
  firestore: 8080,
  storage: 9199,
};

function isPortOpen(port: number): Promise<boolean> {
  return new Promise((resolve) => {
    const socket = new net.Socket();
    socket.setTimeout(1000);
    socket.on('connect', () => {
      socket.destroy();
      resolve(true);
    });
    socket.on('error', () => resolve(false));
    socket.on('timeout', () => resolve(false));
    socket.connect(port, '127.0.0.1');
  });
}

async function waitForPort(port: number, maxMs = 45_000): Promise<void> {
  const deadline = Date.now() + maxMs;
  while (Date.now() < deadline) {
    if (await isPortOpen(port)) return;
    await new Promise((r) => setTimeout(r, 750));
  }
  throw new Error(`[e2e] Port ${port} did not open within ${maxMs}ms`);
}

async function globalSetup(): Promise<void> {
  const firestoreRunning = await isPortOpen(EMULATOR_PORTS.firestore);

  if (!firestoreRunning) {
    console.log('[e2e] Starting Firebase emulators (auth, firestore, storage)...');
    const proc = spawn(
      'npx',
      ['firebase', 'emulators:start', '--only', 'auth,firestore,storage'],
      {
        cwd: WORKSPACE_ROOT,
        stdio: 'pipe',
        detached: false,
      },
    );

    proc.stderr?.on('data', (d: Buffer) => {
      const msg = d.toString();
      if (msg.includes('Error') || msg.includes('error')) {
        process.stderr.write('[emulator] ' + msg);
      }
    });

    fs.mkdirSync(path.dirname(PID_FILE), { recursive: true });
    fs.writeFileSync(PID_FILE, String(proc.pid));

    console.log('[e2e] Waiting for emulators to be ready...');
    await Promise.all([
      waitForPort(EMULATOR_PORTS.auth),
      waitForPort(EMULATOR_PORTS.firestore),
      waitForPort(EMULATOR_PORTS.storage),
    ]);
    console.log('[e2e] Emulators ready.');
  } else {
    console.log('[e2e] Emulators already running — reusing.');
  }

  // Seed Firestore with test data (idempotent — overwrites existing docs).
  console.log('[e2e] Seeding emulator Firestore...');
  execSync('npx nx run seed:emulator', {
    cwd: WORKSPACE_ROOT,
    stdio: 'inherit',
  });
  console.log('[e2e] Seed complete.');
}

export default globalSetup;
